### ISSUE TITLE
[TRACKER] Jenkinsfile rework

### ISSUE THREAD

**Issue by MrKevinWeiss** [RIOT-OS/RobotFW-tests#66]
There are a number of improves that should happen with the CI and specifically Jenkinsfile.
- [ ] Make Jenkinsfile declarative as it is better documented and seems to be preferred
- [ ] Run all tests on nodes before releasing them to prevent async behaviour
- [ ] Tune timeouts (total, node_total, per test)
- [ ] Proper error handling
- [ ] Cancel whole job quickly
- [ ] Build on master and only send binaries
    - [ ] Master can use build in docker to get binaries
    - [ ] Nodes must have a static RIOT folder `/opt/RIOT` used for flashing and `make robot-test`
    - [ ] Master only unstashes RobotFW and binaries in nodes for tests
- [ ] Only run nodes with unique boards
